### ISSUE TITLE
Decoder introduces strange audio artifacts...

### ISSUE THREAD

**Issue by jeffmikels** [EPNW/opus_flutter#1]
Using my plugin (https://github.com/jeffmikels/audiostream) I have been testing the OpusDecoder on Android, and keep running into problems. So I created the following test. When I run it, I get clean sounding audio at first, but the process of encoding and then decoding the audio results in a distorted sound as if the decoded audio is missing samples.

`Audiostream.write(ByteBuffer)` sends PCM audio directly to the Android platform audio system

```dart
Future localOpusPlay() async {
    // sample.raw is 48000 pcm_s16le
    print('sending from sample.raw');
    var data = await rootBundle.load('assets/samples/sample.raw');
    await Audiostream.write(data.buffer);

    print('waiting 2 seconds');
    await Future.delayed(Duration(seconds: 2));
    var frameSize = 1920;
    var offset = 0;
    var decoder = SimpleOpusDecoder(sampleRate: 48000, channels: 2);
    var encoder = SimpleOpusEncoder(
      sampleRate: 48000,
      channels: 2,
      application: Application.audio,
    );
    while (offset < data.lengthInBytes) {
      var length = data.lengthInBytes - offset;
      if (length > frameSize) length = frameSize;
      var packet =
          encoder.encode(input: data.buffer.asInt16List(offset, length));
      offset += length;
      var pcm = decoder.decode(input: packet);
      await Audiostream.write(pcm.buffer);
    }
    encoder.destroy();
    decoder.destroy();
  }
```

**Comment by EPNW** [comment]
I'll take a look tomorrow but my first though is that when using asInt16List you should divide length by 2 since length seem to be in bytes but the length parameter of the .as functions is in elements, not bytes.

**Comment by jeffmikels** [comment]
I did that, and now my code looks like the following and results in playback of the decoded pcm at double-speed.

```dart
Future localOpusPlay() async {
    // sample.raw is 48000 pcm_s16le
    print('sending from sample.raw');
    var data = await rootBundle.load('assets/samples/sample.raw');
    await Audiostream.write(data.buffer);

    print('waiting 2 seconds');
    await Future.delayed(Duration(seconds: 2));
    var decoder = SimpleOpusDecoder(sampleRate: 48000, channels: 2);
    var encoder = SimpleOpusEncoder(
      sampleRate: 48000,
      channels: 2,
      application: Application.audio,
    );

    // will encode the audio data, decode the audio,
    // and put it into a pcmdata array for later playing
    var offset = 0;
    var opusFrameSize = 1920; // in samples
    List<int> pcmdata = [];
    Int16List samples = data.buffer.asInt16List();
    while ((samples.length - offset) >= opusFrameSize) {
      var toEncode = samples.sublist(offset, offset + opusFrameSize);
      var packet = encoder.encode(input: toEncode);
      pcmdata.addAll(decoder.decode(input: packet));
      offset += opusFrameSize;
    }
    await Audiostream.write(Int16List.fromList(pcmdata).buffer);
    encoder.destroy();
    decoder.destroy();
  }
```

**Comment by EPNW** [comment]
Can you upload a repo with all the code neccessary to run your example? Also, are you using the old Audiostream with stereo or the new one with mono? Is the example mono or stereo?

**Comment by jeffmikels** [comment]
https://github.com/jeffmikels/flutter_opus_audio_test

I built a standalone flutter app to demonstrate the problem I'm facing. You should be able to clone, build and run.

**Comment by EPNW** [comment]
Ok, so I think I found the problem.

The documentation of opus states that when decoding using the native opus methods the returned value is the amount of samples decoded (see [here](https://pub.dev/documentation/opus_dart/latest/opus_decoder/opus_decode.html)). But it seems that the returned value is actually the samples per channel, so the total number of samples is channels times the returned value. I'll have to fix this in opus_dart and update opus_flutter accordingly.

**Comment by jeffmikels** [comment]
I'll test it.

**Comment by jeffmikels** [comment]
Excellent! Thanks for your efforts. I now have a working mumble client with clear, low-latency audio.

**Comment by robertnax** [comment]
> Excellent! Thanks for your efforts. I now have a working mumble client with clear, low-latency audio.

@jeffmikels you dont by any chance have that flutter mumble client on github that is running ? i simply cant get anything here working at all

**Comment by jeffmikels** [comment]
> > Excellent! Thanks for your efforts. I now have a working mumble client with clear, low-latency audio.
> 
> @jeffmikels you dont by any chance have that flutter mumble client on github that is running ? i simply cant get anything here working at all 

I'm working on a commercial solution now, but I think I can release some of it to the open. Follow my profile and my organization for updates there. Also, contact me directly if you want help with your own implementation.
