### ISSUE TITLE
Build failed for ios simulator

### ISSUE THREAD

**Issue by ntduy26** [EPNW/opus_flutter#14]
Error: 

Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...                                              5.7s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,753ms
Xcode build done.                                           64.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in
    '/Users/141612/Documents/workaround/opus_test_app/ios/Pods/../.symlinks/plugins/opus_flutter_ios/ios/opus.xcframework opus framework
    ios-i386_x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 x86_64).
    ld: warning: directory not found for option
    '-F/Users/141612/Documents/workaround/opus_test_app/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/opus'
    error: the following command failed with exit code 0 but produced no further output
    Ld
    /Users/141612/Library/Developer/Xcode/DerivedData/Runner-bisyeumpebgqzdfiopgfgqthsscy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/
    opus_flutter_ios.build/Objects-normal/x86_64/Binary/opus_flutter_ios normal x86_64
    ld: warning: directory not found for option
    '-F/Users/141612/Documents/workaround/opus_test_app/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/opus'
    ld: warning: directory not found for option
    '-F/Users/141612/Documents/workaround/opus_test_app/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/opus'
    ld: framework not found opus
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS - 12.5
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (3 available)

• No issues found!

**Comment by janoskranczler** [comment]
Hi @ntduy26 ,
I have the same problem, even with the example app. Did you found any solution?

**Comment by EPNW-Eric** [comment]
See #16, seems to be the same bug
